const productos = [
	{
		Tipo: 'Procesador',
		Marca: 'Intel Core',
		Serie: 'i3',
		Socket: '1151',
		Imagen: 'i3.png',
		Stock: 6,
		Precio: 30000,
	},
	{
		Tipo: 'Procesador',
		Marca: 'Intel Core',
		Serie: 'i5',
		Socket: '1151',
		Imagen: 'i5.png',
		Stock: 6,
		Precio: 25000,
	},
	{
		Tipo: 'Procesador',
		Marca: 'Intel Core',
		Serie: 'i7',
		Socket: '1200',
		Imagen: 'i7.png',
		Stock: 4,
		Precio: 60000,
	},
	{
		Tipo: 'Procesador',
		Marca: 'Intel Core',
		Serie: 'i9',
		Socket: '1200',
		Imagen: 'i9.png',
		Stock: 5,
		Precio: 73000,
	},
	{
		Tipo: 'Procesador',
		Marca: 'AMD Ryzen',
		Serie: '3',
		Socket: 'AM4',
		Imagen: 'r3.png',
		Stock: 8,
		Precio: 37000,
	},
	{
		Tipo: 'Procesador',
		Marca: 'AMD Ryzen',
		Serie: '5',
		Socket: 'AM4',
		Imagen: 'r5.png',
		Stock: 0,
		Precio: 42000,
	},
	{
		Tipo: 'Procesador',
		Marca: 'AMD Ryzen',
		Serie: '7',
		Socket: 'AM4',
		Imagen: 'r7.png',
		Stock: 5,
		Precio: 65000,
	},
	{
		Tipo: 'Procesador',
		Marca: 'AMD Ryzen',
		Serie: '9',
		Socket: 'AM4',
		Imagen: 'r9.png',
		Stock: 7,
		Precio: 78000,
	},
	{
		Tipo: 'Motherboard',
		Marca: 'Asus',
		Serie: 'B85',
		Socket: '1151',
		Imagen: 'B85.png',
		Stock: 2,
		Precio: 20000,
	},
	{
		Tipo: 'Motherboard',
		Marca: 'Gigabyte',
		Serie: 'Z370',
		Socket: '1200',
		Imagen: 'Z370.png',
		Stock: 5,
		Precio: 33000,
	},
	{
		Tipo: 'Motherboard',
		Marca: 'Gigabyte',
		Serie: 'Z590',
		Socket: '1200',
		Imagen: 'Z590.png',
		Stock: 7,
		Precio: 40000,
	},
	{
		Tipo: 'Motherboard',
		Marca: 'Asus',
		Serie: 'B550',
		Socket: 'AM4',
		Imagen: 'B550.png',
		Stock: 6,
		Precio: 25000,
	},
	{
		Tipo: 'Motherboard',
		Marca: 'Asus',
		Serie: 'X570',
		Socket: 'AM4',
		Imagen: 'X570.png',
		Stock: 7,
		Precio: 35000,
	},
	{
		Tipo: 'Motherboard',
		Marca: 'Gigabyte',
		Serie: 'A570',
		Socket: 'AM4',
		Imagen: 'A570.png',
		Stock: 6,
		Precio: 39000,
	},
];
