const productos = [
	{
		Tipo: 'Procesador',
		Marca: 'Intel Core',
		Serie: 'i3',
		Socket: '1151',
		Precio: 30000,
	},
	{
		Tipo: 'Procesador',
		Marca: 'Intel Core',
		Serie: 'i5',
		Socket: '1151',
		Precio: 25000,
	},
	{
		Tipo: 'Procesador',
		Marca: 'Intel Core',
		Serie: 'i7',
		Socket: '1200',
		Precio: 60000,
	},
	{
		Tipo: 'Procesador',
		Marca: 'Intel Core',
		Serie: 'i9',
		Socket: '1200',
		Precio: 73000,
	},
	{
		Tipo: 'Procesador',
		Marca: 'AMD Ryzen',
		Serie: '3',
		Socket: 'AM4',
		Precio: 37000,
	},
	{
		Tipo: 'Procesador',
		Marca: 'AMD Ryzen',
		Serie: '5',
		Socket: 'AM4',
		Precio: 42000,
	},
	{
		Tipo: 'Procesador',
		Marca: 'AMD Ryzen',
		Serie: '7',
		Socket: 'AM4',
		Precio: 65000,
	},
	{
		Tipo: 'Procesador',
		Marca: 'AMD Ryzen',
		Serie: '9',
		Socket: 'AM4',
		Precio: 78000,
	},
	{
		Tipo: 'Motherboard',
		Marca: 'Asus',
		Serie: 'B85',
		Socket: '1151',
		Precio: 20000,
	},
	{
		Tipo: 'Motherboard',
		Marca: 'Gigabyte',
		Serie: 'Z370',
		Socket: '1200',
		Precio: 33000,
	},
	{
		Tipo: 'Motherboard',
		Marca: 'Gigabyte',
		Serie: 'Z590',
		Socket: '1200',
		Precio: 40000,
	},
	{
		Tipo: 'Motherboard',
		Marca: 'Asus',
		Serie: 'B550',
		Socket: 'AM4',
		Precio: 25000,
	},
	{
		Tipo: 'Motherboard',
		Marca: 'Asus',
		Serie: 'X570',
		Socket: 'AM4',
		Precio: 35000,
	},
	{
		Tipo: 'Motherboard',
		Marca: 'Gigabyte',
		Serie: 'A570',
		Socket: 'AM4',
		Precio: 39000,
	},
];
