let productos = [
	{
		Tipo: 'CPU',
		Marca: 'Intel Core',
		Serie: 'i3',
		Socket: ['1151', 'DDR3'],
		Imagen: 'i3.png',
		Precio: 160,
	},
	{
		Tipo: 'CPU',
		Marca: 'Intel Core',
		Serie: 'i5',
		Socket: ['1151', 'DDR3'],
		Imagen: 'i5.png',
		Precio: 235,
	},
	{
		Tipo: 'CPU',
		Marca: 'Intel Core',
		Serie: 'i7',
		Socket: ['1200', 'DDR4'],
		Imagen: 'i7.png',
		Precio: 320,
	},
	{
		Tipo: 'CPU',
		Marca: 'Intel Core',
		Serie: 'i9',
		Socket: ['1200', 'DDR4'],
		Imagen: 'i9.png',
		Precio: 420,
	},
	{
		Tipo: 'CPU',
		Marca: 'AMD Ryzen',
		Serie: '3',
		Socket: ['AM4', 'DDR4'],
		Imagen: 'r3.png',
		Precio: 200,
	},
	{
		Tipo: 'CPU',
		Marca: 'AMD Ryzen',
		Serie: '5',
		Socket: ['AM4', 'DDR4'],
		Imagen: 'r5.png',
		Precio: 300,
	},
	{
		Tipo: 'CPU',
		Marca: 'AMD Ryzen',
		Serie: '7',
		Socket: ['AM4', 'DDR4'],
		Imagen: 'r7.png',
		Precio: 400,
	},
	{
		Tipo: 'CPU',
		Marca: 'AMD Ryzen',
		Serie: '9',
		Socket: ['AM4', 'DDR4'],
		Imagen: 'r9.png',
		Precio: 560,
	},
	{
		Tipo: 'Motherboard',
		Marca: 'Asus',
		Serie: 'B85',
		Socket: ['1151', 'DDR3'],
		Imagen: 'B85.png',
		Precio: 80,
	},
	{
		Tipo: 'Motherboard',
		Marca: 'Gigabyte',
		Serie: 'Z370',
		Socket: ['1200', 'DDR4'],
		Imagen: 'Z370.png',
		Precio: 130,
	},
	{
		Tipo: 'Motherboard',
		Marca: 'Gigabyte',
		Serie: 'Z590',
		Socket: ['1200', 'DDR4'],
		Imagen: 'Z590.png',
		Precio: 240,
	},
	{
		Tipo: 'Motherboard',
		Marca: 'Asus',
		Serie: 'B550',
		Socket: ['AM4', 'DDR4'],
		Imagen: 'B550.png',
		Precio: 195,
	},
	{
		Tipo: 'Motherboard',
		Marca: 'Asus',
		Serie: 'X570',
		Socket: ['AM4', 'DDR4'],
		Imagen: 'X570.png',
		Precio: 330,
	},
	{
		Tipo: 'Motherboard',
		Marca: 'Gigabyte',
		Serie: 'A570',
		Socket: ['AM4', 'DDR4'],
		Imagen: 'A570.png',
		Precio: 250,
	},
	{
		Tipo: 'RAM',
		Marca: 'Kingston',
		Serie: 'Fury',
		Socket: ['All', 'DDR3'],
		Tamaño: '8',
		Imagen: 'Fury.png',
		Precio: 80,
	},
	{
		Tipo: 'RAM',
		Marca: 'Kingston',
		Serie: 'Predator',
		Socket: ['All', 'DDR4'],
		Tamaño: '16',
		Imagen: 'Predator.png',
		Precio: 150,
	},
];
